## experiment setting
date: "0926"
industry: "美妆"
tags: "deepseek_美妆实体验证"
output_dir_path: output

## 实体类型相关信息
mode: "BP" # MBP, P
entity_type: 
  - "品牌"
  - "品类"
num_labels: 5

data:
  format: excel # excel / csv/ pickle  / json
  # raw_data_path: data/raw_data/doc_entity_extraction_expand_test.xlsx  # 输入的实体打标的数据路径
  # vkg_entity_data_path: data/raw_data/correct_entity.xlsx
  
  raw_data_path: data/raw_data/beauty_doc_entity_extraction_expand.xlsx  # 输入的实体打标的数据路径,输入数据的id列必须是“doc_id”,标题必须是“headline”， 内容必须是“content”
  vkg_entity_data_path: data/raw_data/correct_entity.xlsx
  business_entity_dict_path: data/raw_data/business_entity_dict.xlsx # 必须存在entity、entity_type两列

model:
  device: "cuda:0"
  pretrained_model_name: hfl/chinese-roberta-wwm-ext
  pretrain_model_dir: pretrain_model
  max_len: 512
  batch_size: 32
  n_epochs: 3
  lr: 1e-5
  do_training: True
  do_prediction: False

stages:
  # - data_preprocess
  # - entity_word_eval
  # - sentence_include_entity_eval
  # - generate_dataset
  # - train_model
  - model_evaluate
  
data_preprocess:
  processed_file_name: processed_data.xlsx
  
entity_word_eval:
  prompt_path: src/prompt/entity_eval_prompt1.txt
  template_code: 1184
  first_entity_eval_result_file: first_entity_eval_result.xlsx
  
sentence_include_entity_eval:
  split_content_max_length: 300
  template_code: 1190
  entity_type_definition_and_example_file_path: /workspace/gpt-vkg-entity-extraction/config/customized_init/entity_type_definition.csv
  second_entity_eval_result_file: second_entity_eval_result.xlsx
  
generate_dataset:
  threshold: 0.5
  entities_is_null_number: 10000
  train_data: train_dataset
  valid_data: valid_dataset
  test_data: test_dataset
  test_add_keyword_data: test_add_keyword_dataset
  
train_model:
  save_model_dir: model
  model_name: model.pth
  test_data_predict_file: test_no_add_keyword_data_predict_result.pkl

model_evaluate:
  test_no_add_keyword_data_predict_file: test_no_add_keyword_data_predict_result.xlsx
  test_add_keyword_data_predict_file: test_add_keyword_data_predict_result.xlsx


  



